apiVersion: v1
data:
  Dockerfile: |-
    FROM python:3.11-slim

    WORKDIR /app

    # Instalar dependencias del sistema
    RUN apt-get update && apt-get install -y \
        build-essential \
        libpq-dev \
        && rm -rf /var/lib/apt/lists/*

    # Copiar requirements.txt
    COPY requirements.txt .

    # Instalar dependencias de Python
    RUN pip install --no-cache-dir -r requirements.txt

    # Copiar el código del proyecto
    COPY . .

    # Exponer el puerto
    EXPOSE 8000

    # Comando para ejecutar la aplicación
    CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000"]
  manage.py: |
    #!/usr/bin/env python
    """Django's command-line utility for administrative tasks."""
    import os
    import sys


    def main():
        """Run administrative tasks."""
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
        try:
            from django.core.management import execute_from_command_line
        except ImportError as exc:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            ) from exc
        execute_from_command_line(sys.argv)


    if __name__ == '__main__':
        main()
  requirements.txt: |-
    Django==4.2
    djangorestframework==3.14.0
    django-cors-headers==4.2.0
    psycopg2-binary==2.9.10
    Pillow==10.4.0
    djangorestframework-simplejwt==5.2.2
    drf-yasg==1.21.5
    python-dotenv==1.0.0
    gunicorn==21.2.0
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: backend
  name: backend-cm0
