apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - |-
              python manage.py migrate &&
                     python manage.py loaddata products/fixtures/initial_products.json &&
                     python manage.py collectstatic --noinput &&
                     gunicorn backend.wsgi:application --bind 0.0.0.0:8000
          env:
            - name: DEBUG
              value: "1"
            - name: DJANGO_SETTINGS_MODULE
              value: backend.settings
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_NAME
              value: ecommerce_db
            - name: POSTGRES_PASSWORD
              value: Firestone01
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
          image: backend
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: backend-cm0
            - mountPath: /app/staticfiles
              name: static-volume
            - mountPath: /app/media
              name: media-volume
      restartPolicy: Always
      volumes:
        - configMap:
            name: backend-cm0
          name: backend-cm0
        - name: static-volume
          persistentVolumeClaim:
            claimName: static-volume
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-volume
