apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: VITE_API_URL
              value: http://localhost:8000
          image: frontend
          name: frontend
          ports:
            - containerPort: 5173
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: frontend-cm0
            - mountPath: /app/node_modules
              name: frontend-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: frontend-cm0
          name: frontend-cm0
        - name: frontend-claim1
          persistentVolumeClaim:
            claimName: frontend-claim1
